function V = v_e_HF_L(B,E,V0,m,q_e,t,t0,theta2B,w_HF)
% V_E_HF_L - charged-particle velocity in an LHCP HF-wave E-field
% where the wave-frequency is not equal to the gyro-frequency of the
% particle. 
% 
% Calling:
%  V = v_e_HF_L(B,E,V0,m,q_e,t,t0,theta2B,w_HF)
% Input:
%  B       - magnetic field-strangth (T), double scalar
%  E       - HF-wave electrical field amplitude (V/m), duoble scalar
%  V0      - initial particle velocity (m/s), double array [3 x 1]
%  m       - particle mass (kg), double scalar
%  q_e     - particle charge (C), double scalar
%  t       - time (s), double array [1 x n_t]
%  t0      - time-zero, reference-time (s), double scalar.
%  theta2B - angle to the magnetic field of the HF-wave-propagation
%  w_HF    - HF-radio-wave angular frequency (rad/s), double array
% Output:
%   V - velocity (m/s), double array [3 x n_t]
% 
% These velocity-components are obtained by analytical integration
% of the momentum-equations for magnetized particles in an
% Left-hand circular polarized E-field at a frequency that is not
% equal to the particle gyro-frequency (for which resonance would
% occur). The integration is obtained with the aid of the symbolic
% capabillities of matlab~2020:
% %% Physical constants
% syms q_e m positive
% %% Magnetic-field
% syms B real % magnetic-field-strength
% %% E-field parameters
% syms E      real  % HF E-field amplitude
% syms w_HF   positive  % HF frequency
% syms theta2B  real% angle-of-propagation relative to B-field
% %% Time-coordinate
% syms t t0 real
% %% Position and velocity vectorial functions
% syms R(t) [1 3]
% syms V(t) [1 3]
% %% Initial conditions, at t0
% syms R0 [1 3]
% syms V0 [1 3]
% 
% %% Equations of motion
% ODES_L = [diff(R) == V,diff(V) == -q_e/m*(E*[cos((t-t0)*w_HF)*cos(theta2B),sin((t-t0)*w_HF),cos((t-t0)*w_HF)*sin(theta2B)]+cross(V,[0,0,-B]))];
% ODES_R = [diff(R) == V,diff(V) == -q_e/m*(E*[cos((t-t0)*w_HF)*cos(theta2B),-sin((t-t0)*w_HF),cos((t-t0)*w_HF)*sin(theta2B)]+cross(V,[0,0,-B]))];
% I_CONDS = [R(0)==R0,V(0)==V0];
% SOL_L = dsolve(ODES_L,I_CONDS);
% SOL_R = dsolve(ODES_R,I_CONDS);
% V_Lfcn = matlabFunction([SOL_L.V1;SOL_L.V2;SOL_L.V3]);




% These velocity-components are obtained by analytical integration
% of the momentum-equations for magnetized particles in an
% Left-hand circular polarized E-field at a frequency that is not
% equal to the particle gyro-frequency (for which resonance would
% occur). The integration is obtained with the aid of the symbolic
% capabillities of matlab~2020:
% syms R0 [1 3]   % initial particle position
% syms V0 [1 3]   % initial particle velocity
% syms B          % magnetic-field-strength
% syms E          % HF-E-field amplitude
% syms w_HF       % angular frequency of HF-wave
% syms t          % time-variable
% syms R(t) [1 3] % particle trajectory 
% syms V(t) [1 3] % particle velocity "trajectory"
% syms q_e m      % particle charge and mass
% syms theta2B    % HF-wave propagation angle rel B-field
% % Equations of motion, written as coupled first-order ODEs such
% % that the solutions will give v(t) explicitly, for an L-mode
% % polarized E-field
% ODES_L = [diff(R) == V,diff(V) == -q_e/m*(E*[cos((t-t0)*w_HF)*cos(theta2B),sin((t-t0)*w_HF),cos((t-t0)*w_HF)*sin(theta2B)]+cross(V,[0,0,-B]))];
% and an R-mode polarized E-field
% ODES_R = [diff(R) == V,diff(V) == -q_e/m*(E*[cos((t-t0)*w_HF)*cos(theta2B),-sin((t-t0)*w_HF),cos((t-t0)*w_HF)*sin(theta2B)]+cross(V,[0,0,-B]))];
% % Initial conditions
% I_CONDS = [R(0)==R0,V(0)==V0];
% % solutions:
% SOL_L = dsolve(ODES_L,I_CONDS);
% SOL_R = dsolve(ODES_R,I_CONDS);
% V_Lfcn = matlabFunction([SOL_L.V1;SOL_L.V2;SOL_L.V3]);
w_e = w_e_gyro(B);
V = [(B.*E.*q_e.^2.*sin(theta2B+t0.*w_HF+w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) - ...
     (B.*E.*q_e.^2.*sin(theta2B+t0.*w_HF-w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) + ...
     (B.*E.*q_e.^2.*sin(theta2B-t0.*w_HF+w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) - ...
     (B.^2.*V0(1).*q_e.^2.*cos(w_e*t))./...
     (m.^2.*( w_HF.^2 - w_e.^2)) - ...
     (B.^2.*V0(2).*q_e.^2.*sin(w_e*t))./ ...
     (m.^2.*( w_HF.^2 - w_e.^2)) + ...
     (B.*E.*q_e.^2.*sin(-theta2B+t0.*w_HF+w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) + ...
     (V0(1).*m.^2.*w_HF.^2.*cos(w_e*t))./...
     (m.^2.*( w_HF.^2 - w_e.^2)) + ...
     (V0(2).*m.^2.*w_HF.^2.*sin(w_e*t))./ ...
     (m.^2.*( w_HF.^2 - w_e.^2)) + ...
     (B.*E.*q_e.^2.*sin(t.*w_HF-t0.*w_HF))./ ...
     (m.^2.*( w_HF.^2 - w_e.^2)) + ...
     (B.*E.*q_e.^2.*sin(t0.*w_HF+w_e*t))./ ...
     (2*m.^2.*( w_HF.^2 - w_e.^2) ) + ...
     (B.*E.*q_e.^2.*sin(t0.*w_HF-w_e*t))./ ...
     (2*m.^2.*( w_HF.^2 - w_e.^2) ) - ...
     (E.*m.*q_e.*w_HF.*sin(theta2B+t.*w_HF-t0.*w_HF))./ ...
     (2*m.^2.*( w_HF.^2 - w_e.^2) ) + ...
     (E.*m.*q_e.*w_HF.*sin(theta2B-t.*w_HF+t0.*w_HF))./ ...
     (2*m.^2.*( w_HF.^2 - w_e.^2) ) - ...
     (E.*m.*q_e.*w_HF.*sin(theta2B+t0.*w_HF+w_e*t))./ ...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) - ...
     (E.*m.*q_e.*w_HF.*sin(theta2B+t0.*w_HF-w_e*t))./ ...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) + ...
     (E.*m.*q_e.*w_HF.*sin(theta2B-t0.*w_HF+w_e*t))./ ...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) - ...
     (E.*m.*q_e.*w_HF.*sin(-theta2B+t0.*w_HF+w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) - ...
     (E.*m.*q_e.*w_HF.*sin(t0.*w_HF+w_e*t))./ ...
     (2*m.^2.*( w_HF.^2 - w_e.^2) ) + ...
     (E.*m.*q_e.*w_HF.*sin(t0.*w_HF-w_e*t))./...
     (2*m.^2.*( w_HF.^2 - w_e.^2) );                                    % End of v_x
     (B.*E.*q_e.^2.*cos(theta2B+t.*w_HF-t0.*w_HF).*(-1.0./2.0))./ ...
     (m.^2.*( w_HF.^2 - w_e.^2)) - ...
     (B.*E.*q_e.^2.*cos(theta2B-t.*w_HF+t0.*w_HF))./...
     (2*m.^2.*( w_HF.^2 - w_e.^2) ) + ...
     (B.*E.*q_e.^2.*cos(theta2B+t0.*w_HF+w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) + ...
     (B.*E.*q_e.^2.*cos(theta2B+t0.*w_HF-w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) + ...
     (B.*E.*q_e.^2.*cos(theta2B-t0.*w_HF+w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) - ...
     (B.^2.*V0(2).*q_e.^2.*cos(w_e*t))./...
     (m.^2.*( w_HF.^2 - w_e.^2)) + ...
     (B.*E.*q_e.^2.*cos(-theta2B+t0.*w_HF+w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) + ...
     (B.^2.*V0(1).*q_e.^2.*sin(w_e*t))./...
     (m.^2.*( w_HF.^2 - w_e.^2)) + ...
     (V0(2).*m.^2.*w_HF.^2.*cos(w_e*t))./...
     (m.^2.*( w_HF.^2 - w_e.^2)) + ...
     (B.*E.*q_e.^2.*cos(t0.*w_HF+w_e*t))./...
     (2*m.^2.*( w_HF.^2 - w_e.^2) ) - ...
     (B.*E.*q_e.^2.*cos(t0.*w_HF-w_e*t))./...
     (2*m.^2.*( w_HF.^2 - w_e.^2) ) - ...
     (V0(1).*m.^2.*w_HF.^2.*sin(w_e*t))./...
     (m.^2.*( w_HF.^2 - w_e.^2)) - ...
     (E.*m.*q_e.*w_HF.*cos(theta2B+t0.*w_HF+w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) + ...
     (E.*m.*q_e.*w_HF.*cos(theta2B+t0.*w_HF-w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) + ...
     (E.*m.*q_e.*w_HF.*cos(theta2B-t0.*w_HF+w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) - ...
     (E.*m.*q_e.*w_HF.*cos(-theta2B+t0.*w_HF+w_e*t))./...
     (4*m.^2.*(w_HF.^2 - w_e.^2)) + ...
     (E.*m.*q_e.*w_HF.*cos(t.*w_HF-t0.*w_HF))./...
     (m.^2.*( w_HF.^2 - w_e.^2)) - ...
     (E.*m.*q_e.*w_HF.*cos(t0.*w_HF+w_e*t))./...
     (2*m.^2.*( w_HF.^2 - w_e.^2) ) - ...
     (E.*m.*q_e.*w_HF.*cos(t0.*w_HF-w_e*t))./...
     (2*m.^2.*( w_HF.^2 - w_e.^2) );                                    % End of v_y
     V0(3) + ...
     (E.*q_e.*cos(theta2B+t0.*w_HF))./(m.*w_HF.*2.0) - ...
     (E.*q_e.*cos(theta2B-t0.*w_HF))./(m.*w_HF.*2.0) + ...
     (E.*q_e.*cos(theta2B+t.*w_HF-t0.*w_HF))./(m.*w_HF.*2.0) - ...
     (E.*q_e.*cos(theta2B-t.*w_HF+t0.*w_HF))./(m.*w_HF.*2.0)];
